name: Add Issues and PRs to Triage

on:
  issues:
    types:
      - opened
      - reopened
  pull_request_target:
    types:
      - opened
      - reopened

jobs:

  label:
    permissions:
      pull-requests: write
    name: Label PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target'
    steps:
    - uses: actions/labeler@v4.0.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  add-to-project:
    name: Add to Triage Project
    runs-on: ubuntu-latest
    steps:
      - id: check
        env:
          HAS_TRIAGE_PAT: ${{ secrets.TRIAGE_PAT != '' }}
        shell: bash
        if: env.HAS_TRIAGE_PAT == 'true'
        run: |
          echo '::set-output name=triage::1'

      - uses: actions/add-to-project@v0.3.0
        if: steps.check.outputs.triage
        with:
          project-url: https://github.com/orgs/smallstep/projects/94
          github-token: ${{ secrets.TRIAGE_PAT }}
